# Setup
title:               Quantus
tagline:             'A website by Jared Richard'
description:         'Quantus. By Jared Richard - just a Physicist who wants to know why.'
url:                 http://jaredrichard.co.uk
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jared Richard
  url:               
  email:             jaredk.richard@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
