# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Quantus
tagline:          By Jared Richard
description:      A site by <a href="www.linkedin.com/in/jared-richard">Jared Richard</a>
url:              http://jaredrichard.co.uk

author:
  name:           Jared Richard
  url:           

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet